package com.example.trainshowsurvey.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single survey submission.
 *
 * @param id A unique identifier for the survey entry. This is auto-generated by the database
 *           and is used internally to manage the data. It is not shown to the user.
 * @param timestamp The time the survey was submitted, in milliseconds since the epoch.
 * @param sources A comma-separated string of the options the user selected for how they
 *                heard about the show.
 */
@Entity(tableName = "surveys")
data class Survey(
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val timestamp: Long,
    val sources: String
)